// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {goFiles} from '../models';

export function GetBase64OfImage(arg1:string):Promise<goFiles.ImageResponse>;

export function GetDefaultDirs():Promise<goFiles.FileDataMap>;

export function GetFiles(arg1:string):Promise<Array<goFiles.FileData>>;

export function GetFirstFrameOfGif(arg1:string):Promise<string>;

export function GetPath(arg1:string):Promise<string>;

export function OpenFile(arg1:string):Promise<void>;
