// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetBase64OfImage(arg1) {
  return window['go']['goFiles']['Files']['GetBase64OfImage'](arg1);
}

export function GetDefaultDirs() {
  return window['go']['goFiles']['Files']['GetDefaultDirs']();
}

export function GetFiles(arg1) {
  return window['go']['goFiles']['Files']['GetFiles'](arg1);
}

export function GetPath(arg1) {
  return window['go']['goFiles']['Files']['GetPath'](arg1);
}

export function OpenFile(arg1) {
  return window['go']['goFiles']['Files']['OpenFile'](arg1);
}
