// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {goFiles} from '../models';

export function GetFiles(arg1:string):Promise<Array<goFiles.FileData>>;
