// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Searchdir(arg1) {
  return window['go']['goFiles']['fuzzySearch']['Searchdir'](arg1);
}
