// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {goFiles} from '../models';

export function Searchdir(arg1:string):Promise<Array<goFiles.dirData>>;
